language:
  node_js
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN    
before_script:
  - npm install -g codecov 
jobs:
  include:
    - stage: Test coverage
      script:
        - ng test --browsers=ChromeHeadlessNoSandbox --codeCoverage=true --watch=false
      after_script: 
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi  