# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Blog-Build-Script CI

on:
  push:
    branches: [ version-1 ]
  pull_request:
    branches: [ version-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    - name: Install npm dependencies 
      run: npm ci # Using npm ci is generally faster than running npm install
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Launch Unit Tests 
      run: npm test 

    - name: Send mail to notify CI/CD termination
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.ionos.fr
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Blog4Engineer FRONTEND PIC 
        body: Build job of [ ${{github.repository}} ] completed with status [ ${{job.status}} ]
        to: hacene.upmc@gmail.com
        from: Blog4EngineerCreator PIC
        content_type: text/html