# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Blog-Build-Script CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    - name: Install npm dependencies 
      run: npm ci # Using npm ci is generally faster than running npm install
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Launch Unit Tests 
      run: npm test --watch=false --code-coverage

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        if: success()
      run: |
        curl -s https://codecov.io/bash | bash
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      shell: bash